### ISSUE TITLE
Uncaught TypeError: ns.charCodeAt is not a function

### ISSUE THREAD

**Issue by andy1028** [thysultan/stylis.js#50]
![image](https://user-images.githubusercontent.com/13925688/28607147-081db1b6-720d-11e7-95e4-5b0007fd2615.png)

**Comment by thysultan** [comment]
The signature of the first argument is a string, so that's expected. What did you pass to it?

**Comment by andy1028** [comment]
im not sure，probably not this fun error;

this error was trow in `styled-components` which use `stylis.js`

**Comment by thysultan** [comment]
Have you tried to install the latest `styled-components`? Maybe it's fixed upstream, otherwise i'd suggest opening an issue there.

**Comment by andy1028** [comment]
[styled-components/issues/1033](https://github.com/styled-components/styled-components/issues/1033)

**Comment by andy1028** [comment]
Yes, above issues is in `styled-components`  with version 2.1.1 (latest) ,and work well in version 2.1.0

**Comment by andy1028** [comment]
thanks for replied! i guess above issues will be `styled-components` self

**Comment by thysultan** [comment]
I feel like the issue could be a dependency cache issue with npm since the screenshot you posted doesn't look like the latest version of stylis. 

Can you confirm that the dependency stylis is at version 3.2.8? 

I say this because there was a release of styled-components that relies on a new feature of stylis, specifically this [https://github.com/styled-components/styled-components/pull/962](https://github.com/styled-components/styled-components/pull/962). So if the stylis dependency did not update locally then that might be the problem.

**Comment by andy1028** [comment]
![image](https://user-images.githubusercontent.com/13925688/28612606-67818a1e-7222-11e7-8631-8ad2c95653ab.png)

**Comment by thysultan** [comment]
I meant `node_modules/stylis/package.json` If it's < 3.2.0 either try to npm install styled-components again/ npm install stylis to update it specifically.

**Comment by andy1028** [comment]
![image](https://user-images.githubusercontent.com/13925688/28612918-4d237262-7223-11e7-86e9-f900978de3c8.png)

**Comment by thysultan** [comment]
Since the error was from [stringifyRules.js#L5](https://github.com/styled-components/styled-components/blob/28b51827da35120d7c17942c90b33dc343b7865f/src/utils/stringifyRules.js#L5), it was probably because the dependency did not update, can you still reproduce the error after updating?

**Comment by andy1028** [comment]
yes the error still reproduce after updating

**Comment by thysultan** [comment]
I think it's exactly as philpl said, beyond that, a repo with the problem would help. But i don't think the problem is from this end.
